import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <nav className="bg-slate-50 py-4">
                    <div className="max-w-5xl mx-auto text-xl space-x-4">
                        {[
                            { path: "/model", name: "模型" },
                            { path: "/dataset", name: "数据集" },
                        ].map(({ path, name }) => (
                            <Link
                                key={path}
                                href={path}
                                className="transition-colors hover:text-primary hover:font-medium"
                            >
                                {name}
                            </Link>
                        ))}
                    </div>
                </nav>
                <div className="max-w-5xl mx-auto">{children}</div>
            </body>
        </html>
    );
}
